### ISSUE TITLE
Transfer repo to dokku-community

### ISSUE THREAD

**Issue by josegonzalez** [dokku-community/dokku-git-rev#3]
Hi! I was hoping you'd transfer the repository to the dokku-community organization. It will serve as a hub for plugins that may no longer get the attention they need from their maintainers, and hopefully allow us to provide better testing of said plugins going forward.

Once transferred, I can ensure this is up to date with the latest changes from the rest of the community :)

**Comment by nornagon** [comment]
Sure thing! Thanks for reaching out :)

**Comment by nornagon** [comment]
Hrm, I got this error message:

<img width="375" alt="options" src="https://cloud.githubusercontent.com/assets/172800/20642179/0bc6faf2-b3bd-11e6-98ba-11a1ca5c5060.png">

I've added you as a collaborator on this repository, perhaps you can transfer it?

**Comment by nornagon** [comment]
I also tried transferring it to you directly, but you already have a fork, so apparently that doesn't work :)

<img width="315" alt="options" src="https://cloud.githubusercontent.com/assets/172800/20642196/52ad05ec-b3bd-11e6-9a3c-a20809e898af.png">

**Comment by josegonzalez** [comment]
Added you as admin on that org.

**Comment by nornagon** [comment]
![options](https://cloud.githubusercontent.com/assets/172800/20916742/1e0b0bea-bb42-11e6-8a89-e8cc14d26a97.png)
This is what I get now :/

**Comment by josegonzalez** [comment]
Updated

**Comment by nornagon** [comment]
Done :)

**Comment by AxelTheGerman** [comment]
@josegonzalez @nornagon the readme and [dokku plugin docs](http://dokku.viewdocs.io/dokku/community/plugins/#plugins-implementing-new-dokku-functionality) still link to `cjblomqvist/dokku-git-rev` repo.

Also quick question: If a plugin requires the git rev, should it require this plugin to be installed for now or duplicate the functionality and wait until it ships with dokku - any timeline on that?

**Comment by josegonzalez** [comment]
Mind making PRs to the readme and docs?

Re: plugin functionality timeline, it'll be done when it's done. Be the change you wish to see in the world :)

**Comment by AxelTheGerman** [comment]
will make a PR for readme and docs 👍 

re git-rev plugin: what needs to be done to get it into dokku core? Any missing functionality or design decisions, or "just" merging it in and probably writing tests (would appreciate some help/pointers for that)

**Comment by josegonzalez** [comment]
New plugins need to be written in golang, but thats about it.
