### ISSUE TITLE
GIT_REV is one revision behind

### ISSUE THREAD

**Issue by zarqman** [dokku-community/dokku-git-rev#6]
We're seeing GIT_REV show up for the application always one revision behind (on dokku 0.9.4).

On a `git push`:
app is built
app is released
app is deployed
GIT_REV is updated

The problem is that the app deployment happens before GIT_REV is updated, so it picks up the prior revision instead of the current one.

Using a hook that's earlier in the process might fix that part, but also risks updating GIT_REV when the deploy ends up failing later. Perhaps the ENV var could be written to /etc/profile.d/git_rev.sh, so that it's always in sync with the deployment image?

**Comment by josegonzalez** [comment]
You didn't install git-rev properly. You need to install it using the *exact* instructions in the readme. In particular, you forgot the part where we specify the name of the plugin as it is to be installed.
